name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: false

      - name: Build
        run: cargo build --verbose

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run unit tests
        run: cargo test

      - name: Run feature tests
        run: |
          cargo install cargo-test-all-features
          cargo +nightly test-all-features
